# Generated by Django 5.1.4 on 2024-12-08 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_no', models.IntegerField(db_column='Account_No', primary_key=True, serialize=False)),
                ('balance', models.DecimalField(blank=True, db_column='Balance', decimal_places=2, max_digits=10, null=True)),
                ('acc_type', models.CharField(blank=True, db_column='Acc_Type', max_length=20, null=True)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.IntegerField(db_column='Branch_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('assets', models.DecimalField(blank=True, db_column='Assets', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Branch1',
            fields=[
                ('branch_id', models.IntegerField(db_column='Branch_Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
            ],
            options={
                'db_table': 'branch_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Branch2',
            fields=[
                ('address', models.CharField(db_column='Address', max_length=255, primary_key=True, serialize=False)),
                ('assets', models.DecimalField(blank=True, db_column='Assets', decimal_places=2, max_digits=15, null=True)),
                ('mgr_ssn', models.IntegerField(blank=True, db_column='Mgr_SSN', null=True)),
            ],
            options={
                'db_table': 'branch_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cust1',
            fields=[
                ('ssn', models.IntegerField(db_column='SSN', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('apt_no', models.IntegerField(blank=True, db_column='Apt_No', null=True)),
                ('st_no', models.IntegerField(blank=True, db_column='St_no', null=True)),
            ],
            options={
                'db_table': 'cust_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cust2',
            fields=[
                ('apt_no', models.IntegerField(db_column='Apt_No', primary_key=True, serialize=False)),
                ('st_no', models.IntegerField(db_column='St_no')),
                ('city', models.CharField(blank=True, db_column='City', max_length=30, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=20, null=True)),
                ('zip', models.IntegerField(blank=True, db_column='Zip', null=True)),
            ],
            options={
                'db_table': 'cust_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ssn', models.IntegerField(db_column='SSN', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('apt_no', models.IntegerField(blank=True, db_column='Apt_no', null=True)),
                ('street_no', models.IntegerField(blank=True, db_column='Street_no', null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=20, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=30, null=True)),
                ('zip', models.IntegerField(blank=True, db_column='Zip', null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ssn', models.IntegerField(db_column='SSN', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('phone_no', models.CharField(blank=True, db_column='Phone_No', max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, db_column='Start_Date', null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emp1',
            fields=[
                ('ssn', models.IntegerField(db_column='Ssn', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, db_column='Start_Date', null=True)),
                ('branch_id', models.IntegerField(blank=True, db_column='Branch_id', null=True)),
                ('manager_ssn', models.IntegerField(blank=True, db_column='Manager_SSN', null=True)),
            ],
            options={
                'db_table': 'emp_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emp2',
            fields=[
                ('ssn', models.IntegerField(db_column='Ssn', primary_key=True, serialize=False)),
                ('phone_no', models.CharField(blank=True, db_column='Phone_no', max_length=20, null=True)),
            ],
            options={
                'db_table': 'emp_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trans_code', models.IntegerField(db_column='Trans_Code', primary_key=True, serialize=False)),
                ('trans_date', models.DateField(blank=True, db_column='Trans_Date', null=True)),
                ('hour', models.IntegerField(blank=True, db_column='Hour', null=True)),
                ('trans_type', models.CharField(blank=True, db_column='Trans_Type', max_length=20, null=True)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=2, max_digits=10, null=True)),
                ('chargeable', models.CharField(blank=True, db_column='Chargeable', max_length=10, null=True)),
            ],
            options={
                'db_table': 'transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Checking',
            fields=[
                ('account_no', models.OneToOneField(db_column='Account_No', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bankk.account')),
                ('overdraft', models.DecimalField(blank=True, db_column='Overdraft', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'checking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('account_no', models.OneToOneField(db_column='Account_No', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bankk.account')),
                ('monthly_repay', models.DecimalField(blank=True, db_column='Monthly_Repay', decimal_places=2, max_digits=10, null=True)),
                ('loan_amt', models.DecimalField(blank=True, db_column='Loan_Amt', decimal_places=2, max_digits=10, null=True)),
                ('fin_int_rate', models.DecimalField(blank=True, db_column='Fin_Int_Rate', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'loan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoneyMarket',
            fields=[
                ('account_no', models.OneToOneField(db_column='Account_No', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bankk.account')),
                ('variable_int_rate', models.DecimalField(blank=True, db_column='Variable_Int_Rate', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'money_market',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('account_no', models.OneToOneField(db_column='Account_No', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bankk.account')),
                ('fixed_int_rate', models.DecimalField(blank=True, db_column='Fixed_Int_Rate', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'savings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('ssn', models.OneToOneField(db_column='SSN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bankk.customer')),
                ('last_access_date', models.DateField(blank=True, db_column='Last_Access_Date', null=True)),
            ],
            options={
                'db_table': 'customer_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('essn', models.OneToOneField(db_column='ESSN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bankk.employee')),
                ('name', models.CharField(db_column='Name', max_length=50)),
            ],
            options={
                'db_table': 'dependent',
                'managed': False,
            },
        ),
    ]
